[package]
name = "llt-rs"
version = "0.5.0"
edition = "2024"
description = "Low-Latency Primitives Toolkit for Rust"
license = "MIT"
readme = "README.md"
repository = "https://github.com/aodr3w/llt-rs"
homepage = "https://github.com/aodr3w/llt-rs"
authors = ["Andrew Odiit <andrewodiit2020@gmail.com>"]

# SEO Metadata
keywords = ["lock-free", "concurrency", "ring-buffer", "spsc", "low-latency"]
categories = ["concurrency", "data-structures"]

[dependencies]
crossbeam-utils = "0.8"
core_affinity = { version = "0.8", optional = true }


[features]
# By default, only the bare-metal RingBuffer is compiled.
default = []
# The "channel" feature enables the hybrid, blocking SPSC Channel (requires std).
channel = []

# The "object-pool" feature enables the object-pool module (requires std).
object_pool = []

# The "arena_allocator" feature enables the arena_allocator module (requires std).
arena_allocator = []

affinity = ["dep:core_affinity"]
